version: '3.4'

services:
  
  sqldb:
    image: mcr.microsoft.com/mssql/server
    container_name: sqldb
    platform: windows/x86_64
    ports:
      - "1433:1433" 
    environment:
      SA_PASSWORD: "Abc12345678+"
      ACCEPT_EULA: "Y"

  shop:
    image: ${DOCKER_REGISTRY-}shop
    build:
      context: .
      dockerfile: Shop/Dockerfile
    container_name: shop
    platform: windows/x86_64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqldb;Database=CateringDB_Prod;User Id=sa;Password=Abc12345678+"
    depends_on:
      - sqldb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro